"""Theme system for Kairos TUI — 4 built-in skin definitions.

Each skin defines color overrides for the dark theme.
Applied via Textual CSS variable injection at runtime.
"""

from __future__ import annotations

from typing import Any

# ═══════════════════════════════════════════════════════════════
# Skin definitions
# ═══════════════════════════════════════════════════════════════

TUI_SKINS: dict[str, dict[str, Any]] = {
    "default": {
        "name": "Default",
        "accent": "#5e6ad2",
        "accent_bright": "#7170ff",
        "bg": "#08090a",
        "panel": "#0f1011",
        "surface": "#191a1b",
        "text": "#f7f8f8",
        "text2": "#d0d6e0",
        "text3": "#8a8f98",
        "text4": "#62666d",
        "green": "#27a644",
        "yellow": "#f5a623",
        "red": "#e5484d",
        "border": "#1e1e24",
        "agent_prefix": "🤖 Kairos",
        "user_prefix": "You",
    },
    "hacker": {
        "name": "Hacker",
        "accent": "#00ff41",
        "accent_bright": "#39ff14",
        "bg": "#0a0a0a",
        "panel": "#0d0d0d",
        "surface": "#111111",
        "text": "#00ff41",
        "text2": "#00cc33",
        "text3": "#009926",
        "text4": "#00661a",
        "green": "#00ff41",
        "yellow": "#ffff00",
        "red": "#ff0000",
        "border": "#003300",
        "agent_prefix": "🤖 KAIROS",
        "user_prefix": ">",
    },
    "retro": {
        "name": "Retro",
        "accent": "#00ffff",
        "accent_bright": "#ff00ff",
        "bg": "#000033",
        "panel": "#000044",
        "surface": "#000055",
        "text": "#ffffff",
        "text2": "#00ffff",
        "text3": "#ff00ff",
        "text4": "#8888cc",
        "green": "#00ff88",
        "yellow": "#ffff00",
        "red": "#ff4444",
        "border": "#444488",
        "agent_prefix": "🤖 Kairos",
        "user_prefix": "You",
    },
    "minimal": {
        "name": "Minimal",
        "accent": "#ffffff",
        "accent_bright": "#ffffff",
        "bg": "#000000",
        "panel": "#000000",
        "surface": "#111111",
        "text": "#cccccc",
        "text2": "#aaaaaa",
        "text3": "#666666",
        "text4": "#444444",
        "green": "#aaaaaa",
        "yellow": "#999999",
        "red": "#888888",
        "border": "#333333",
        "agent_prefix": "Kairos",
        "user_prefix": ">",
    },
}


def get_skin(name: str) -> dict[str, Any]:
    """Get skin by name, falling back to default."""
    return TUI_SKINS.get(name, TUI_SKINS["default"])


def build_skin_css(skin: dict[str, Any]) -> str:
    """Generate Textual CSS overrides for a skin.

    Injects CSS variables that override the base theme colors.
    """
    return f"""
    /* Auto-generated by theme.py — skin: {skin['name']} */
    Screen {{
        background: {skin['bg']};
    }}
    #sidebar {{
        background: {skin['panel']};
        border-right: solid {skin['border']};
    }}
    #sidebar-brand {{
        color: {skin['accent']};
        border-bottom: solid {skin['border']};
    }}
    #sidebar-sessions, #sidebar-tools {{
        background: {skin['panel']};
        border-bottom: solid {skin['border']};
    }}
    Tree {{
        background: {skin['panel']};
    }}
    Tree > .tree--label {{
        color: {skin['text3']};
    }}
    TreeNode {{
        color: {skin['text2']};
    }}
    TreeNode:hover {{
        background: {skin['surface']};
    }}
    #sidebar-model {{
        color: {skin['text3']};
        border-top: solid {skin['border']};
    }}
    #header-extra {{
        background: {skin['panel']};
    }}
    #header-model {{
        color: {skin['text3']};
    }}
    RichLog {{
        background: {skin['bg']};
        color: {skin['text2']};
    }}
    #input-area {{
        background: {skin['panel']};
        border-top: solid {skin['border']};
    }}
    #prompt-label {{
        color: {skin['accent']};
    }}
    Input {{
        background: {skin['surface']};
        color: {skin['text']};
        border: solid {skin['border']};
    }}
    Input:focus {{
        border: solid {skin['accent']};
    }}
    #status-bar {{
        background: {skin['panel']};
        border-top: solid {skin['border']};
        color: {skin['text4']};
    }}
    #transcript {{
        scrollbar-color: {skin['border']};
        scrollbar-color-hover: {skin['text4']};
        scrollbar-color-active: {skin['accent']};
    }}
    #header-thinking {{
        color: {skin['yellow']};
    }}
    """
